name: The Summit Church Denver
favicon: null
layout_spectrum: 0.21142670535482466
typography_spectrum: 0.45539035904221237
title: The Summit Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2780119557864964
  lightness: 0.01874537719413638
  saturation: 0.4732133587822318
  rhythmicContrast: 0.8905433944892138
purpose: []
